### ISSUE TITLE
保存chatbot模型时，有尝试使用tf.saved_model这个api来保存吗？

### ISSUE THREAD

**Issue by StephenLee2016** [sudongqi/TensorFlow_ChatBot#1]
你好，我最近在训练一个chatbot，打算用tensorflow serving 来部署这个模型，但是serving只支持exporter和saved_model这两个api保存的格式。所以你可以给点建议吗？谢谢

**Comment by sudongqi** [comment]
我去年写的时候好像还没有这个API，所以用了比较土的方法，saved_model我看了一下很方便，应当是兼容的。

**Comment by StephenLee2016** [comment]
因为和官方说明文档有些不同，在chatbot中encoder和decoder我不确定定义的输入和输出是什么，虽然我现在可以用saved_model导出模型，但是加载预测的时候会报错，所以肯定还是在指定输入和输出时出了问题，如果可以的话，麻烦你帮助看下？因为现在saved_model相关的说明文档很少，尝试了好久都没有解决！如果你方便的话，可以发送我你的联系方式吗？

**Comment by sudongqi** [comment]
我可以试一下

**Comment by sudongqi** [comment]
我刚才试了一下，saved_model可以加载（你可以用get_tensor_by_name），但是输出的结果有问题。主要原因是test.py里的beam search用的是纯python的代码（不属于tensorflow graph的一部分），如果用saved_model加载则要先从保存的模型里提取enc_state, dec_state的handler。比较奇怪的是，enc_state是一个叫LSTMStateTuple的class，里边包含hidden state和memory cell两个tensor，虽然tensor可以单独拿出来，但是这个tuple似乎拿不出来，如果用两个tensor新建一个state则有可能就不是原来的state,所以我也不知道如何改, 之前听说官方要把beam search写成operation? 如果有这个operation就可能可以解决这个问题。

**Comment by StephenLee2016** [comment]
感谢你的尝试，现在确实问题是这样的，模型可以保存，可以加载，但是进行不了预测。不太确定到底问题出在哪里，对于chatbot模型的服务器部署，不知道你有过相关经验吗？

**Comment by sudongqi** [comment]
我对网络的东西是绝对外行，但之前用flask socket部署过这个模型（就是前后端互传string），不过代码没有上传，前段时间又搞坏了电脑。再我看来，chatbot用seq2seq做不靠谱，娱乐性大于实用性。
