### ISSUE TITLE
s2s_reader.py why create buckets_list that are not used?

### ISSUE THREAD

**Issue by skyap** [sudongqi/TensorFlow_ChatBot#4]
Hi, 
function "def create_bucket" create a list of of tuples with the length equal to number of option power two(6^2 = 36). Then it is use in function "def __init__" of class reader to create "self.bucket_list", which will expect to have length of 36 but the actual bucket we want to use is (5,10) , (10, 15), (15,20), (20,25) and (25,31) , which denote as bucket 0,1,2,3,4,5, respectively in "def build_bucket_dict". 

why we create the "self.bucket_list" to have 36 empty list while we just need 6 empty list? do i miss something in the code? Thank you!

best regards,
Yap

**Comment by sudongqi** [comment]
I don't quiet remember what I did before, but I guess my original intention is to use 36 (6^2) bucket options instead of just 6.

**Comment by skyap** [comment]
Thanks for your reply!
